#!/usr/bin/env node
'use strict';
/* ==========================================================================
   scripts/build-client.js — assemble the static client for Cloudflare Pages.

   Produces dist/ containing exactly what the browser needs (index.html +
   shared/ + client/ + docs/) plus the edge config (_headers, _redirects,
   404.html) from public/. No bundler: the client is dependency-free ES5/HTML,
   so "build" is a deterministic copy — fast, cache-friendly, nothing to break.
   ========================================================================== */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'dist');

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function copy(src, dst) {
  const s = fs.statSync(src);
  if (s.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const f of fs.readdirSync(src)) copy(path.join(src, f), path.join(dst, f));
  } else {
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.copyFileSync(src, dst);
  }
}

rmrf(OUT);
fs.mkdirSync(OUT, { recursive: true });

// game client
for (const item of ['index.html', 'shared', 'client', 'docs']) {
  copy(path.join(ROOT, item), path.join(OUT, item));
}
// edge config (flattened to the publish root)
for (const item of fs.readdirSync(path.join(ROOT, 'public'))) {
  copy(path.join(ROOT, 'public', item), path.join(OUT, item));
}

// Inject the default backend URL for the hosted client. Cloudflare Pages exposes
// BACKEND_URL as a build environment variable; we normalize http(s):// to
// ws(s):// and bake it into client/config.js so the public site auto-points at
// your Cloudflare Tunnel. With no BACKEND_URL the committed empty default ships
// and players simply enter the address in the lobby.
const backend = (process.env.BACKEND_URL || '').trim();
if (backend) {
  const ws = backend.replace(/^http(s?):\/\//i, (_, s) => 'ws' + s + '://');
  const js = '/* Generated by scripts/build-client.js from BACKEND_URL. */\n' +
    'window.GEARWORKS_DEFAULT_SERVER = ' + JSON.stringify(ws) + ';\n';
  fs.writeFileSync(path.join(OUT, 'client', 'config.js'), js);
  console.log('injected default server -> ' + ws);
}

const count = (function walk(p) {
  let n = 0;
  for (const f of fs.readdirSync(p)) {
    const fp = path.join(p, f);
    n += fs.statSync(fp).isDirectory() ? walk(fp) : 1;
  }
  return n;
})(OUT);

console.log(`built client -> dist/ (${count} files)`);
