#!/usr/bin/env node
'use strict';
/* ==========================================================================
   scripts/build-client.js — assemble the static client for Cloudflare Pages.

   Produces dist/ containing exactly what the browser needs (index.html +
   shared/ + client/ + docs/) plus the edge config (_headers, _redirects,
   404.html) from public/. No bundler: the client is dependency-free ES5/HTML,
   so "build" is a deterministic copy — fast, cache-friendly, nothing to break.
   ========================================================================== */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'dist');

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function copy(src, dst) {
  const s = fs.statSync(src);
  if (s.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const f of fs.readdirSync(src)) copy(path.join(src, f), path.join(dst, f));
  } else {
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    fs.copyFileSync(src, dst);
  }
}

rmrf(OUT);
fs.mkdirSync(OUT, { recursive: true });

// game client
for (const item of ['index.html', 'shared', 'client', 'docs']) {
  copy(path.join(ROOT, item), path.join(OUT, item));
}
// edge config (flattened to the publish root)
for (const item of fs.readdirSync(path.join(ROOT, 'public'))) {
  copy(path.join(ROOT, 'public', item), path.join(OUT, item));
}

// Inject runtime config for the hosted client from Cloudflare Pages build vars:
//   BACKEND_URL   — default game-server address (normalized http(s)->ws(s)).
//   DISCOVERY_URL — stable pointer the client fetches to auto-discover the
//                   CURRENT server (wins over BACKEND_URL when set). Bake a
//                   fixed pointer URL here once; its contents rotate.
// With neither set, the committed empty defaults ship (players enter the
// address in the lobby, or same-origin/localhost applies).
const backendRaw = (process.env.BACKEND_URL || '').trim();
const discovery = (process.env.DISCOVERY_URL || '').trim();
if (backendRaw || discovery) {
  const backend = backendRaw ? backendRaw.replace(/^http(s?):\/\//i, (_, s) => 'ws' + s + '://') : '';
  const js = '/* Generated by scripts/build-client.js from BACKEND_URL / DISCOVERY_URL. */\n' +
    'window.GEARWORKS_DEFAULT_SERVER = ' + JSON.stringify(backend) + ';\n' +
    'window.GEARWORKS_DISCOVERY_URL = ' + JSON.stringify(discovery) + ';\n';
  fs.writeFileSync(path.join(OUT, 'client', 'config.js'), js);
  if (backend) console.log('injected default server -> ' + backend);
  if (discovery) console.log('injected discovery url -> ' + discovery);
}

const count = (function walk(p) {
  let n = 0;
  for (const f of fs.readdirSync(p)) {
    const fp = path.join(p, f);
    n += fs.statSync(fp).isDirectory() ? walk(fp) : 1;
  }
  return n;
})(OUT);

console.log(`built client -> dist/ (${count} files)`);
